services:
  - type: web
    name: talkbot-backend
    env: node
    buildCommand: "npm run build"
    startCommand: "n8n start"
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: galqu123
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 3000
        
